### ISSUE TITLE
Feature: Runner

### ISSUE THREAD

**Issue by AndreCostaaa** [plx-pdg/plx#59]
A worker that should be capable of launching a program and returning the output

**Comment by samuelroland** [comment]
My guess concerning the design of this runner is:
1. It should be language agnostic
1. The inputs should be 
   1. an array of arguments to run the process (java has no binary the command should be generated in another module depending on the exo type (xmake or java)). Ex: `['java', '-classpath', 'out', 'Main']`.
   1. an array of additional string arguments: like `['Joe', '4']`
1. To enable progressive output display (it case the program is taking several seconds): It should generate an event each time a piece of output is produced. When the last piece of output has been read and the program exit, the event should return this piece and include the exit code. 
1. In case of a crash this is very important to have the begin output. In case there is a segfault (some exo examples `crash` have this) we should be able to display it. When I run an example with Fish I get this custom message `fish: Job 1, './out/crash' terminated by signal SIGSEGV (Address boundary error)`, so this is probably doable.
1. In your tests, use the `examples/` files in C, and to generate the binaries as the compilation module is far from ready, you can spawn `gcc` process until we have a better solution. I guess testing with other languages is pointless, because future end-to-end tests will make sure we can actually work with the 3 languages.

I guess stdin injection is for another PR, this is another non-trivial feature to implement.
